# -*- coding: utf-8 -*-
"""Intensify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rzYJP99zj_qlu7coERTKYwQk6SDGiHQJ
"""

pip install xarray netCDF4 cfgrib cdsapi copernicusmarine xgboost cartopy

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ~/.cdsapirc
# url: https://cds.climate.copernicus.eu/api
# key: 800619b6-78cf-42be-ae17-9a8a70eddd91

import xarray, pandas, numpy, torch, sklearn, xgboost

import os
import cdsapi; c = cdsapi.Client()
output_filename = "era5_test_2m_temp.nc"

print("Sending NetCDF request to Copernicus servers...")
try:
    c.retrieve(
        'reanalysis-era5-single-levels',
        {
            'product_type': 'reanalysis',
            'variable': '2m_temperature',
            'year': '2023',
            'month': '06',
            'day': '15',
            'time': '12:00',
            'area':[15, 75, 10, 80],       # 5°x5° box over India region
            'format': 'netcdf',             # Switched to NetCDF
            'grid': [0.25, 0.25],           # Ensures proper lat-lon formatting for NetCDF
        },
        output_filename
    )

    # Verify file downloaded locally in Colab
    if os.path.exists(output_filename):
        print(f"\n✅ Success! NetCDF File downloaded successfully.")
        print(f"📁 Location: {os.path.abspath(output_filename)}")
        print(f"⚖️ File Size: {os.path.getsize(output_filename) / 1024:.2f} KB")
    else:
        print("\n❌ Process complete, but file could not be found.")

except Exception as e:
    print(f"\n❌ Retrieval Failed: {e}")

import xarray as xr
xr.open_dataset('/content/era5_test_2m_temp.grib')

!pip install tropycal

import pandas as pd
from tropycal import tracks

# ==============================================================================
# 1. CONFIGURATION: Specify the North Indian cyclones you need for your project
# ==============================================================================
CYCLONE_LIST = [
    ("Amphan", 2020),
    ("Fani", 2019),
    ("Mocha", 2023),
    ("Remal", 2024),
    ("Hudhud", 2014)
]

# ==============================================================================
# 2. FETCH TRACK DATASET USING TROPYCAL
# ==============================================================================
print("Connecting to NOAA NCEI servers via Tropycal... (Initializing Global Dataset)")
# Tropycal fetches a more reliable NetCDF/mirror stream under the hood
ib_data = tracks.TrackDataset(basin='all', source='ibtracs')

all_cyclone_dfs = []
successful_downloads = 0

# Retain precisely the target columns requested
COLUMNS_TO_KEEP = ['SID', 'NAME', 'ISO_TIME', 'LAT', 'LON', 'WMO_WIND', 'USA_WIND']

print("\n--- Starting Batch Processing ---")

# ==============================================================================
# 3. LOOP THROUGH CYCLONES & MAP TO RAW FIELD NAMES
# ==============================================================================
for name, year in CYCLONE_LIST:
    try:
        # Search for the storm object
        storm = ib_data.get_storm((name.lower(), year))

        # Convert Tropycal's internal object to a structural DataFrame
        df = storm.to_dataframe()

        # Map Tropycal's standard tracking headers back to your exact requested IBTrACS names
        # Tropycal uses standard names: 'date' -> ISO_TIME, 'lat' -> LAT, 'lon' -> LON, 'vmax' -> USA_WIND
        df['SID'] = storm.id
        df['NAME'] = storm.name.upper()
        # Fix: 'date' column is not found, use 'time' instead
        df['ISO_TIME'] = pd.to_datetime(df['time'])
        df['LAT'] = df['lat']
        df['LON'] = df['lon']

        # Fix: 'vmax' column is not found, use 'wmo_vmax' for USA_WIND
        if 'wmo_vmax' in df.columns:
            df['USA_WIND'] = df['wmo_vmax']
        else:
            df['USA_WIND'] = None # Or handle as per requirements if no wind data

        # Handle WMO_WIND mapping: 'wmo_wind' is not found, use 'wmo_vmax' as fallback
        if 'wmo_wind' in df.columns:
            df['WMO_WIND'] = df['wmo_wind']
        elif 'wmo_vmax' in df.columns:
            df['WMO_WIND'] = df['wmo_vmax']
        else:
            df['WMO_WIND'] = df['USA_WIND'] # Fallback to USA_WIND if no specific WMO wind is found

        # Filter strictly to 6-hour synoptic intervals (00, 06, 12, 18 UTC)
        six_hourly_df = df[df['ISO_TIME'].dt.hour.isin([0, 6, 12, 18])].copy()

        # Convert date column formatting back into portable strings
        six_hourly_df['ISO_TIME'] = six_hourly_df['ISO_TIME'].dt.strftime('%Y-%m-%d %H:%M:%S')

        # Keep only the columns you actually need
        optimized_df = six_hourly_df[COLUMNS_TO_KEEP].copy()

        # Save a clean standalone backup CSV to your Google Colab folder
        indiv_filename = f"ibtracs_NI_{storm.name.upper()}_{year}_clean_6hrs.csv"
        optimized_df.to_csv(indiv_filename, index=False)
        print(f"🎉 Processed and saved: {storm.name.title()} ({year}) -> {indiv_filename}")

        all_cyclone_dfs.append(optimized_df)
        successful_downloads += 1

    except Exception as e:
        # Fallback check: If the lowercase lookup fails, let's look through the keys directly
        print(f"❌ Error matching '{name}' ({year}). Details: {e}")

# ==============================================================================
# 4. EXPORT MASTER DATASET
# ==============================================================================
print("\n--- Summary ---")
if all_cyclone_dfs:
    master_df = pd.concat(all_cyclone_dfs, ignore_index=True)

    master_filename = "ibtracs_NI_selected_cyclones_clean_6hrs.csv"
    master_df.to_csv(master_filename, index=False)

    print(f"✅ Successfully compiled {successful_downloads}/{len(CYCLONE_LIST)} cyclones!")
    print(f"📁 Master file saved as: '{master_filename}'")
    print(f"Total data rows gathered across all storms: {len(master_df)}")

    # Structural preview of your final optimized columns
    print("\n--- Data Structure Preview ---")
    print(master_df.head(10))
else:
    print("No cyclones were successfully matched and downloaded.")

